Fix out of bounds error when Alacritty windows are resized.
This fixes an error when Alacritty crashes due to an out of bounds error:

```
alacritty git:(master) ✗ RUST_BACKTRACE=1 ./target/debug/alacritty
[unhandled osc_dispatch]: [['1','0',],['?',],] at line 784
[unhandled osc_dispatch]: [['1','1',],['?',],] at line 797
thread 'main' panicked at 'Out of bounds access', src/libcore/option.rs:839:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: <core::option::Option<T>>::expect
             at /build/rust/src/rustc-1.22.1-src/src/libcore/option.rs:302
  11: <alloc::vec_deque::VecDeque<A> as core::ops::index::Index<usize>>::index
             at /build/rust/src/rustc-1.22.1-src/src/liballoc/vec_deque.rs:2365
  12: <alacritty::grid::Grid<T>>::get_visible_line
             at src/grid.rs:601
  13: <alacritty::term::RenderableCellsIter<'a> as core::iter::iterator::Iterator>::next
             at src/term/mod.rs:336
  14: alacritty::renderer::RenderApi::render_cells
             at src/renderer/mod.rs:827
  15: alacritty::display::Display::draw::{{closure}}
             at src/display.rs:364
  16: alacritty::renderer::QuadRenderer::with_api
             at src/renderer/mod.rs:658
  17: alacritty::display::Display::draw
             at src/display.rs:357
  18: alacritty::run
             at src/main.rs:202
  19: alacritty::main
             at src/main.rs:53
  20: __rust_maybe_catch_panic
  21: std::panicking::try
  22: std::rt::lang_start
  23: main
  24: __libc_start_main
  25: _start
thread 'pty reader' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
➜  alacritty git:(master) ✗
```